# fly.toml file generated for sprint-name-2 on 2023-02-08T02:49:03Z

app = "sprint-name-2"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  source="sprintdata2"
  destination="/data"

[build.args]
  DATABASE_URL='file:/data/sprintname.db'

[env]
  PORT='8080'
  ORIGIN='https://sprintna.me'
  DATABASE_URL='file:/data/sprintname.db'

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
